netty:
  port: 8989
url:
  getOfficeById:  http://127.0.0.1/paoffice/office/getById.do
  saveOffice: http://127.0.0.1/paoffice/office/saveOffice.do

# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
    timeout: 3000ms
    cluster:
      nodes:
        - 192.168.25.133:7001
        - 192.168.25.133:7002
        - 192.168.25.133:7003
        - 192.168.25.133:7004
        - 192.168.25.133:7005
        - 192.168.25.133:7006
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms
